version: "3.9"
services:
  nginx_con:
    image: nginx:1.23-alpine

    ports:
     #- "80:80"
      - "443:443"
    volumes:
      - "./nginx.confd/nginx-https.conf:/etc/nginx/conf.d/default.conf"
      - "./ssl/nginx_test.key:/etc/ssl/private/nginx_test.key"
      - "./ssl/nginx_test.pem:/etc/ssl/certs/nginx_test.pem"
        # create ssl certs
        #openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx_test.key -out /etc/ssl/certs/nginx_test.crt
    depends_on:
      - bot

  bot:
    image: python:3.9.16-alpine3.16
    volumes:
      - "../bot.py:/app/app.py"
      - "../req.txt:/app/req.txt"

    #ports:
    #  - "5000:5000"
    expose:
      - "5001"
    env_file:
      - "../.env"
    working_dir: /app
    command: sh -c "
      apk add --no-cache gcc musl-dev linux-headers  &&
      pip install -r req.txt &&
      python3 -v app.py
      "
