version: "3.9"
services:
  nginx_con:
    image: nginx:1.23-alpine

    ports:
#      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.confd/nginx-https.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/ssl/private/nginx_test.key:/etc/ssl/private/nginx_test.key"
      - "/etc/ssl/certs/nginx_test.pem:/etc/ssl/certs/nginx_test.pem"
# create ssl certs
#openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx_test.key -out /etc/ssl/certs/nginx_test.crt
    depends_on:
      - bot
    #user: root
    #command: chmod +x /entrypoint.sh
    #entrypoint: /entrypoint.sh

  bot:
    image: python:3.9.16-alpine3.16
    volumes:
      - "../bot.py:/app/app.py"
      - "../req.txt:/app/req.txt"

    expose:
      - "5000"
    env_file:
      - ".env"
#    environment:
#      - FLASK_APP=app.py
#      - FLASK_RUN_HOST=0.0.0.0
    working_dir: /app
    command: sh -c "
      apk add --no-cache gcc musl-dev linux-headers  &&
      pip install -r req.txt && 
      gunicorn --bind 0.0.0.0:5000 --workers=3 app:start_webhook"

